### ISSUE TITLE
Can you add translation files

### ISSUE THREAD

**Issue by q1085909155** [eyal282/SQLite-Bans#1]
I want to have this plugin in other languages to make it more convenient for people in my country to play games

**Comment by eyal282** [comment]
> I want to have this plugin in other languages to make it more convenient for people in my country to play games

I'll check a possibility to do that.

**Comment by q1085909155** [comment]
> > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> 
> I'll check a possibility to do that.

Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job

**Comment by eyal282** [comment]
> > > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> > 
> > 
> > I'll check a possibility to do that.
> 
> Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job

I'll finish the discord unban and ungag logger and attach the sm_ban thing. The translations should be done later.

**Comment by eyal282** [comment]
> > > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> > 
> > 
> > I'll check a possibility to do that.
> 
> Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job


The ban menu with !ban is now completed. I will close this pull request despite not finishing the translations. It's a hard thing to do and I don't feel like doing it until I find another developer to help me.

**Comment by eyal282** [comment]
> > > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> > 
> > 
> > I'll check a possibility to do that.
> 
> Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job

I started translating, Please grab the latest .sp & include & translations from here, and compile it: https://github.com/eyal282/SQLite-Bans/tree/developer

This is an experimental version, please test it and report back issues.

Also, add my discord: Eyal282#1334 let's discuss the whole thing.

**Comment by q1085909155** [comment]
> > > > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> > > 
> > > 
> > > I'll check a possibility to do that.
> > 
> > 
> > Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job
> 
> I started translating, Please grab the latest .sp & include & translations from here, and compile it: https://github.com/eyal282/SQLite-Bans/tree/developer
> 
> This is an experimental version, please test it and report back issues.
> 
> Also, add my discord: Eyal282#1334 let's discuss the whole thing.

I have loaded the developer version on my server, the translation is not working, is it version 3.3? This version doesn't! Ban menu

**Comment by eyal282** [comment]
> > > > > I want to have this plugin in other languages to make it more convenient for people in my country to play games
> > > > 
> > > > 
> > > > I'll check a possibility to do that.
> > > 
> > > 
> > > Thank you, and one more request: when I type sm_ban, a menu of ban players will pop up, just like the original. In addition, your plug-in is doing a good job
> > 
> > 
> > I started translating, Please grab the latest .sp & include & translations from here, and compile it: https://github.com/eyal282/SQLite-Bans/tree/developer
> > This is an experimental version, please test it and report back issues.
> > Also, add my discord: Eyal282#1334 let's discuss the whole thing.
> 
> I have loaded the developer version on my server, the translation is not working, is it version 3.3? This version doesn't! Ban menu

Send me a discord, let's discuss what's wrong.

My discord is: Eyal282#1334
